app:
  name: food-supply-chain
  environment: development

server:
  port: 8080
  timeout:
    read: 5s
    write: 10s
    idle: 120s

database:
  host: localhost
  port: 5433
  user: supplychain
  password: supplychain123
  name: supplychain
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime: 1h

nats:
  url: nats://localhost:4222
  cluster_id: supply-chain-cluster
  client_id: supply-chain-client
  subject_prefix: supply.chain

auth:
  jwt_secret: your-secret-key-here
  token_expiry: 1h
  refresh_token_expiry: 24h

services:
  inventory:
    name: inventory-service
    port: 8080
    health_check_interval: 30s
    metrics_port: 9090

  shipment:
    name: shipment-service
    port: 8081
    health_check_interval: 30s
    metrics_port: 9091

  gateway:
    name: api-gateway
    port: 3000
    health_check_interval: 30s
    metrics_port: 9092

logging:
  level: debug
  format: json
  output: stdout

metrics:
  enabled: true
  prometheus_port: 9090

tracing:
  enabled: true
  jaeger:
    service_name: ${APP_NAME}
    agent_host: localhost
    agent_port: 6831
